# Generated by Django 4.0 on 2021-12-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='black_player',
            new_name='black_player_id',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='white_player',
            new_name='white_player_id',
        ),
        migrations.RenameField(
            model_name='playergamemove',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='playergamemove',
            old_name='player',
            new_name='player_id',
        ),
    ]
