# Generated by Django 4.0 on 2022-01-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_black_player_game_black_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='game.player'),
        ),
    ]
