# Generated by Django 4.0 on 2022-01-03 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0003_alter_game_black_player_id_alter_game_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergamemove',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='black_player_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='white_player_id',
        ),
        migrations.RemoveField(
            model_name='playergamemove',
            name='player_id',
        ),
        migrations.AddField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='auth.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='created_by_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_player', to='auth.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 21, 29, 50, 534894)),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='auth.user'),
        ),
        migrations.AddField(
            model_name='playergamemove',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
