# Generated by Django 4.0 on 2022-01-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0004_rename_game_id_playergamemove_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_player', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='registration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='playergamemove',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
